name: Deploy Web UI

on:
  push:
    branches:
      - main
    paths:
      - "assignment_16/**"
      - ".github/workflows/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout only assignment_16
        run: |
          git init
          git remote add origin https://github.com/${{ github.repository }}
          git config core.sparseCheckout true
          echo "assignment_16" >> .git/info/sparse-checkout
          git fetch origin
          git branch -r
          git checkout -b main origin/main



      - name: Docker hub login
        run: echo "${{ secrets.DOCKER_KEY }}" | docker login -u "${{ secrets.DOCKER_NAME }}" --password-stdin

      - name: Debug working directory
        run: |
          pwd
          ls -lah
          ls -lah assignment_16


      - name: Build Docker image
        run: |
          docker buildx build --platform linux/amd64 \
            -t ${{ secrets.DOCKER_NAME }}/web_ui:latest \
            -f ./assignment_16/frontend/Dockerfile ./assignment_16/frontend

      - name: Push docker image
        run: |
          docker push nekoreec/web_ui:latest

      






     
